#include "param.h"
#include "main.h"
#include "../../util/common.h"
#include "../../acp/command/main.h"

/*
 * -user_config:
 * put parameters for each channel in this array
 * ChannelParam structure members:
 * id,
 * enable: YES or NO,
 * display_kind: DEVICE_KIND_MAX7219 or DEVICE_KIND_TM1637 or DEVICE_KIND_DSERIAL,
 * display_p1: DIN pin for display_kind=DEVICE_KIND_MAX7219; DIO pin for display_kind=DEVICE_KIND_TM1637,
 * display_p2: CLK pin for display_kind=DEVICE_KIND_MAX7219; CLK pin for display_kind=DEVICE_KIND_TM1637,
 * display_p3: CS pin for display_kind=DEVICE_KIND_MAX7219,
 * display_text_alignment: DISPLAY_ALIGNMENT_LEFT or DISPLAY_ALIGNMENT_RIGHT,
 * serial_id: SERIAL_ID0 or SERIAL_ID1 or SERIAL_ID2 or SERIAL_ID3
 * mode: CHANNEL_MODE_SPY or CHANNEL_MODE_CLIENT or CHANNEL_MODE_SERVER,
 * remote_id (for mode=CHANNEL_MODE_SPY or mode=CHANNEL_MODE_CLIENT),
 * command: CMD_GETR_CHANNEL_FTS or CMD_GETR_CHANNEL_STATE or CMD_GETR_CHANNEL_ERROR or CMD_SET_CHANNEL_GOAL, (set commands are only for mode=CHANNEL_MODE_SPY, get commands are for mode=CHANNEL_MODE_SPY or mode=CHANNEL_MODE_CLIENT)
 * time: timeout (ms) for mode=CHANNEL_MODE_SPY or mode=CHANNEL_MODE_SERVER; poll interval (ms) for mode=CHANNEL_MODE_CLIENT,
 */
const ChannelParam CHANNEL_DEFAULT_PARAMS[] = {
	//{51, YES, 21, DEVICE_KIND_MAX7219, DISPLAY_ALIGNMENT_RIGHT, 3,4,5, CHANNEL_MODE_CLIENT, CMD_GETR_CHANNEL_ERROR, 3000, SERIAL_ID1},
	//{52, YES, 22, DEVICE_KIND_MAX7219, DISPLAY_ALIGNMENT_RIGHT, 3,4,6, CHANNEL_MODE_CLIENT, CMD_GETR_CHANNEL_ERROR, 3000, SERIAL_ID1},
	//{53, YES, 23, DEVICE_KIND_MAX7219, DISPLAY_ALIGNMENT_RIGHT, 3,4,7, CHANNEL_MODE_CLIENT, CMD_GETR_CHANNEL_ERROR, 3000, SERIAL_ID1},
	
	{51, YES, DEVICE_KIND_TM1637, 4,3,0, DISPLAY_ALIGNMENT_RIGHT, SERIAL_ID1, CHANNEL_MODE_CLIENT, 21, CMD_GETR_CHANNEL_FTS, 3000},
	{52, YES, DEVICE_KIND_TM1637, 6,5,0, DISPLAY_ALIGNMENT_RIGHT, SERIAL_ID1, CHANNEL_MODE_CLIENT, 22, CMD_GETR_CHANNEL_FTS, 3000},
	{53, YES, DEVICE_KIND_TM1637, 8,7,0, DISPLAY_ALIGNMENT_RIGHT, SERIAL_ID1, CHANNEL_MODE_CLIENT, 23, CMD_GETR_CHANNEL_FTS, 3000},
};

#define CHANNEL_COUNT (sizeof CHANNEL_DEFAULT_PARAMS / sizeof CHANNEL_DEFAULT_PARAMS[0])
